on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout the repository
        uses: https://data.forgejo.org/actions/checkout@v6
        with:
          github-server-url: https://github.com
          repository: AFKBETO/Orsted-Deno
          token: ${{ secrets.GITHUBPAT }}
          submodules: recursive
          clean: true

      - name: Login to registry
        shell: bash
        run: |
          echo ${{ secrets.CONTAINER_PAT }} | docker login -u ${{ secrets.CONTAINER_USER }} --password-stdin ${{ secrets.REGISTRY }}


      - name: Build Dockerfile and push
        env:
          IMAGE_NAME: orsted
          TAG: latest
        shell: bash
        run: |
          docker build -t ${{ secrets.REGISTRY }}/${{ secrets.OWNER }}/${IMAGE_NAME}:${TAG} .
          docker push ${{ secrets.REGISTRY }}/${{ secrets.OWNER }}/${IMAGE_NAME}:${TAG}

      - name: Cleanup
        shell: bash
        if: always()
        run: |
          docker logout ${{ secrets.REGISTRY }}
